#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Demo.Provider.Service/ && \
    dotnet build src/Demo.Provider.Service/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Demo.Provider.Service/Demo.Provider.Service.csproj --launch-profile web"
