/*
 * API for Demo
 *
 * # Goal This API Description is used as the basis to show code generating use-cases.   <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Demo.Consumer.Client.Model;
using Demo.Consumer.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Demo.Consumer.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PersonAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersonAddress
        //private PersonAddress instance;

        public PersonAddressTests()
        {
            // TODO uncomment below to create an instance of PersonAddress
            //instance = new PersonAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonAddress
        /// </summary>
        [Fact]
        public void PersonAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersonAddress
            //Assert.IsType<PersonAddress>(instance);
        }


        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'HouseNumber'
        /// </summary>
        [Fact]
        public void HouseNumberTest()
        {
            // TODO unit test for the property 'HouseNumber'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

    }

}
