/*
 * API for Demo
 *
 * # Goal This API Description is used as the basis to show code generating use-cases.   <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Demo.Consumer.Client.Model;
using Demo.Consumer.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Demo.Consumer.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PersonName
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonNameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersonName
        //private PersonName instance;

        public PersonNameTests()
        {
            // TODO uncomment below to create an instance of PersonName
            //instance = new PersonName();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonName
        /// </summary>
        [Fact]
        public void PersonNameInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersonName
            //Assert.IsType<PersonName>(instance);
        }


        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'Lastname'
        /// </summary>
        [Fact]
        public void LastnameTest()
        {
            // TODO unit test for the property 'Lastname'
        }

    }

}
