/*
 * API for Demo
 *
 * # Goal This API Description is used as the basis to show code generating use-cases.   <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Demo.Consumer.Client.Model;
using Demo.Consumer.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Demo.Consumer.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Person
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Person
        //private Person instance;

        public PersonTests()
        {
            // TODO uncomment below to create an instance of Person
            //instance = new Person();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Person
        /// </summary>
        [Fact]
        public void PersonInstanceTest()
        {
            // TODO uncomment below to test "IsType" Person
            //Assert.IsType<Person>(instance);
        }


        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Fact]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'EMail'
        /// </summary>
        [Fact]
        public void EMailTest()
        {
            // TODO unit test for the property 'EMail'
        }

    }

}
